AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: My Python Lambda Function

Resources:
  DemoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      FunctionName: DemoLambdaFunction

Outputs:
  DemoLambdaFunctionArn:
    Value:
      Fn::GetAtt:
        - DemoLambdaFunction
        - Arn
