AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: My Python Lambda Function

Resources:
  Github-to-Lmabda-Demo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: .
      FunctionName: Github-to-Lmabda-Demo

Outputs:
  Github-to-Lmabda-DemoArn:
    Value:
      Fn::GetAtt:
        - Github-to-Lmabda-Demo
        - Arn
